import type { Metadata } from "next";
import { Geist, Geist_Mono, Quintessential } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";

const font = Quintessential({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        <Header/>
        <div className="relative z-30">{children}</div>
        <Footer/>
      </body>
    </html>
  );
}
